name: Self-hosted runners smoke test

on:
  workflow_dispatch:

jobs:
  on-runner1:
    runs-on: [self-hosted]
    steps:
      - name: Show context
        run: |
          echo "Hostname: $(hostname)"
          uname -a

  on-runner2:
    runs-on: [self-hosted]
    steps:
      - name: Show context
        run: |
          echo "Hostname: $(hostname)"
          uname -a
